# Generated by Django 5.0.1 on 2024-01-20 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='speech_part',
            field=models.CharField(null=True),
        ),
    ]
