# Generated by Django 5.0.1 on 2024-02-17 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('occurrence', models.PositiveIntegerField()),
                ('speech_part', models.CharField(max_length=1024, null=True)),
            ],
        ),
    ]
