# Generated by Django 5.0.1 on 2024-08-25 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images_mode', '0004_category_main_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagebackup',
            options={'default_manager_name': 'objects'},
        ),
    ]
