name: Easy Deploy to Kamatera
on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      deploy_confirmation:
        description: 'Type "yes" to confirm deployment'
        required: true
      update_git_only:
        description: 'Only update git without deploying?'
        required: true
        default: 'no'
      pull_changes:
        description: 'Pull latest changes?'
        required: true
        default: 'yes'
      make_migrations:
        description: 'Make new migrations?'
        required: true
        default: 'no'
      run_migrations:
        description: 'Run database migrations?'
        required: true
        default: 'no'
      restart_backend:
        description: 'Restart backend server?'
        required: true
        default: 'no'
      rebuild_frontend:
        description: 'Rebuild and restart frontend?'
        required: true
        default: 'yes'
      restart_nginx:
        description: 'Restart Nginx?'
        required: true
        default: 'no'
      install_new_packages:
        description: 'Install new npm packages?'
        required: true
        default: 'no'

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || github.event.inputs.deploy_confirmation == 'yes'
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup SSH
      env:
        SSH_PRIVATE_KEY: ${{ secrets.KAMATERA_SSH_PRIVATE_KEY }}
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/kamatera_key
        chmod 600 ~/.ssh/kamatera_key
        ssh-keyscan -H ${{ secrets.KAMATERA_HOST }} >> ~/.ssh/known_hosts

    - name: Deploy to Kamatera
      env:
        HOST: ${{ secrets.KAMATERA_HOST }}
        USER: ${{ secrets.KAMATERA_USER }}
      run: |
        ssh -i ~/.ssh/kamatera_key $USER@$HOST << EOF
          # Navigate to your project directory
          cd /root/freestyle_fusion/polish_freestyle_app
          # Pull the latest changes
          if [ "${{ github.event.inputs.pull_changes }}" == "yes" ] || [ "${{ github.event_name }}" == "push" ]; then
            echo "Pulling latest changes..."
            git pull origin main
          fi
          # Exit if only updating git
          if [ "${{ github.event.inputs.update_git_only }}" == "yes" ]; then
            echo "Git updated. Exiting without further deployment actions."
            exit 0
          fi
          # Activate virtual environment
          source /root/freestyle_fusion/polish_freestyle_app/backend/venv/bin/activate
          # Make migrations
          if [ "${{ github.event.inputs.make_migrations }}" == "yes" ]; then
            echo "Making migrations..."
            python manage.py makemigrations
          fi
          # Run Django migrations
          if [ "${{ github.event.inputs.run_migrations }}" == "yes" ]; then
            echo "Running migrations..."
            python manage.py migrate
          fi
          # Restart the backend server
          if [ "${{ github.event.inputs.restart_backend }}" == "yes" ]; then
            echo "Restarting backend..."
            screen -S backend -X stuff $'\003'
            screen -S backend -X stuff 'python manage.py runserver 0.0.0.0:8000\n'
          fi
          # Install new npm packages and rebuild frontend
          if [ "${{ github.event.inputs.install_new_packages }}" == "yes" ] || [ "${{ github.event.inputs.rebuild_frontend }}" == "yes" ] || [ "${{ github.event_name }}" == "push" ]; then
            echo "Installing new npm packages and rebuilding frontend..."
            cd frontend
            npm install
            npm run build
          fi
          # Restart frontend
          if [ "${{ github.event.inputs.rebuild_frontend }}" == "yes" ] || [ "${{ github.event_name }}" == "push" ]; then
            echo "Restarting frontend..."
            screen -S frontend -X stuff $'\003'
            screen -S frontend -X stuff 'npm start\n'
          fi
          # Restart Nginx
          if [ "${{ github.event.inputs.restart_nginx }}" == "yes" ]; then
            echo "Restarting Nginx..."
            sudo systemctl restart nginx
          fi
        EOF

    - name: Cleanup
      if: always()
      run: rm -f ~/.ssh/kamatera_key

    - name: Verify Deployment
      run: echo "Deployment steps completed. Verify the changes at your server's IP or domain."