name: Deploy and Migrate

on:
  push:
    branches:
      - main  # or your production branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r backend/requirements.txt

    - name: Run Django migrations
      run: |
        cd backend
        python manage.py migrate

    - name: Build React Native app
      run: |
        cd frontend
        npm install
        npm run build

    - name: Deploy to Ubuntu server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          cd /path/to/your/project
          git pull origin main
          # Update backend
          cd backend
          pip install -r requirements.txt
          python manage.py migrate
          # Update frontend
          cd ../frontend
          npm install
          npm run build
          # Restart your services (e.g., gunicorn, nginx)
          sudo systemctl restart gunicorn
          sudo systemctl restart nginx

    - name: Sync media files
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        source: "backend/media/"
        target: "/path/to/your/project/backend/"