name: Fixed SSH Connection Test
on: [workflow_dispatch]

jobs:
  test_ssh:
    runs-on: ubuntu-latest
    steps:
    - name: Debug SSH connection
      env:
        HOST: ${{ secrets.KAMATERA_HOST }}
        USER: ${{ secrets.KAMATERA_USER }}
        SSH_PRIVATE_KEY: ${{ secrets.KAMATERA_SSH_PRIVATE_KEY }}
      run: |
        echo "Debugging SSH connection..."
        echo "Host is: $HOST"
        echo "User is: $USER"
        
        # Set up SSH key
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/kamatera_key
        chmod 600 ~/.ssh/kamatera_key
        
        # Attempt SSH connection with verbose logging
        ssh -vvv -o StrictHostKeyChecking=no -i ~/.ssh/kamatera_key $USER@$HOST "echo 'SSH connection successful'"
        
        # Clean up
        rm ~/.ssh/kamatera_key